### PR TITLE
Auth0 update

### PR DESCRIPTION
**Pull request by evansiroky**
## Update Auth0

Update to auth0-lock 10 and implement automatic silent authentication renewal.  Refactor routing to be synchronous, but respond to updates within the react lifecycle.  Requires complementing server update in https://github.com/catalogueglobal/datatools-server/pull/24.

## Testing improvements

Add tests for new auth0 and user management.

## Changes to config files

Alphabetize the following files:
- configurations/default/settings.yml
- i18n/english.yml
- i18n/espanol.yml
- i18n/francais.yml

## Etc

- Added better error handling in a few places
- Fix lint errors

### CODE REVIEW

**Comment by evansiroky** [comment]
One thing I forgot to mention is that this change requires a change to the Auth0 JsonWebToken Signature Algorithm from HS256 to RS256.

**Comment by landonreed** [comment]
A couple of issues/questions for you @evansiroky:

- on log out, I get a redirection error screen from Auth0.  Do I need to change something in Auth0?
- could you detail/or link to the change needed for Auth0 token algorithm?
- on first log in from root domain, the previous behavior was to redirect the user automatically to `localhost:9966/home`.  This isn't happening for me.

**Comment by landonreed** [comment]
@evansiroky what is this `{title}` shown in auth0 lock? 
image

**Comment by landonreed** [comment]
Hey @evansiroky the redirect to home was working ok, but earlier this week the issue I mentioned was the following:

1. Visit some deep link while not logged in, e.g., `http://localhost:9966/project`
2. Log in
3. Site first renders the root page, then redirects to `http://localhost:9966/project`.

Previous behavior was that it would only render `http://localhost:9966/project` and not first go to the root page.  This is the issue that needs fixing.

**Comment by landonreed** [comment]
@evansiroky I just tested changing the signing algorithm for MTC staging and it looks like there would be integration issues with changing to `RS256`. I received a `401` status from the MTC server when requesting alerts with token in the auth header; however, when I switched it back to `HS256` everything worked fine again.

So, if you could do some more testing with the silent auth renewal and make sure everything goes smoothly when that fails due to the wrong signing algorithm, I think that would be the next step towards getting auth0 updates merged in.

**Comment by landonreed** [comment]
@evansiroky, I just changed the base to the maintenance branch `dev_v2.0.x` and fixed the merge conflicts.  Let me know here if there are any issues with changing the signing algorithm back to HS256.

FYI, we'll also need to merge this branch (or parts of it) into `sql-editor` to ensure the changes make their way into the next version (edit: this is happening in #67).

**Pull request merged**
